DROP DATABASE GESTION_NUTRICIONISTA;
CREATE DATABASE GESTION_NUTRICIONISTA;
USE GESTION_NUTRICIONISTA;

CREATE TABLE PERFILES
(ID_PERFIL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL
);

CREATE TABLE USUARIOS
(ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(45) NOT NULL UNIQUE,
PASSWORD VARCHAR(45) NOT NULL,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
NOMBRE VARCHAR(50),
DIRECCION VARCHAR(100),
ENABLED INT NOT NULL DEFAULT 1,
FECHA_REGISTRO DATE
);

CREATE TABLE USUARIO_PERFILES
(USERNAME VARCHAR(50) NOT NULL,
ID_PERFIL INTEGER NOT NULL,
PRIMARY KEY(USERNAME, ID_PERFIL),
FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME),
FOREIGN KEY(ID_PERFIL) REFERENCES PERFILES(ID_PERFIL)
);

CREATE TABLE NUTRICIONISTAS
(ID_NUTRICIONISTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
APELLIDOS VARCHAR(45) NOT NULL,
FECHA_NACIMIENTO DATE,
FECHA_ALTA DATE,
ACTIVO INT DEFAULT 1,
DNI VARCHAR(45) NOT NULL UNIQUE,
TELEFONO INT(45) NOT NULL UNIQUE,
SUELDO DEC(9,2)
);

CREATE TABLE CLIENTES
(ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
APELLIDOS VARCHAR(45) NOT NULL,
FECHA_NACIMIENTO DATE,
FECHA_ALTA DATE,
ULTIMA_CONSULTA DATE,
DNI VARCHAR(9) NOT NULL UNIQUE,
TELEFONO INT(45) NOT NULL UNIQUE
);

CREATE TABLE BONOS
(ID_BONO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CANTIDAD_CONSULTAS INT(50) NOT NULL,
CONSULTAS_RESTANTES INT(50) NOT NULL,
ACTIVOS INT(255),
FECHA_ALTA DATE,
ID_CLIENTE INT NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE CONSULTAS
(ID_CONSULTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_NUTRICIONISTA INT NOT NULL,
FOREIGN KEY(ID_NUTRICIONISTA) REFERENCES NUTRICIONISTAS(ID_NUTRICIONISTA),
ID_CLIENTE INT NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FECHA_CONSULTA DATE,
PRECIO DEC(9,2),
PORCENTAJE_VARIABLE DEC(9,2),
ID_BONO INT,
FOREIGN KEY(ID_BONO) REFERENCES BONOS(ID_BONO),
DURACION INT
);

